config:
  table_manager:
    retention_deletes_enabled: true
    retention_period: 168h
  limits_config:
    ingestion_rate_mb: 16
    ingestion_burst_size_mb: 32

persistence:
  enabled: true
  size: 10Gi

resources:
  requests:
    memory: 512Mi

serviceMonitor:
  enabled: true
